### ISSUE TITLE
[Entscheidung] Lojbanparser

### ISSUE THREAD

**Issue by uwap** [lojbanistan/lojbanistan.de#11]
Wenn wir noch schönere möglichkeiten bieten wollen, wäre es cool, wenn wir jeden lojban satz auch noch durch einen lojbanparser jagen würden. auf die art könnte man klammerung etc. pp. gut darstellen. Es gibt da einersatz http://hackage.haskell.org/package/lojban, andererseits http://hackage.haskell.org/package/lojbanParser, http://hackage.haskell.org/package/zasni-gerna und http://hackage.haskell.org/package/tersmu. So wie ich das nur gesehen habe, funktionieren die alle nicht mit GHC8. Wir sollten uns also überlegen ob wir einen alten lojban parser portieren oder einen neuen schreiben.

Siehe auch: #6

**Comment by Profpatsch** [comment]
Porten sollte in jedem Fall die schnellere Methode sein. Man sollte sich halt vorher auf einen festlegen, um den Aufwand nicht zweimal zu haben.

**Comment by uwap** [comment]
Ich denke auch, dass einen vorhanden parser porten einfacher wäre. Vielleicht sollten wir insbesondere mit der überlege wie einfach es wäre dem hinten rausfallenen datentypen eine ToHTML instanze zu geben.

**Comment by Profpatsch** [comment]
`lojbanParser` scheint einfach nur ein neuerer `zasni-germa` zu sein. https://github.com/YoshikuniJujo/zasni-gerna/issues/1

**Comment by Profpatsch** [comment]
https://hackage.haskell.org/package/lojban ist für das Parsen von jbovlaste und ein paar andere misc-dinge. Ist halt ein bisschen anmaßend von Chris Done, sich dafür gleich den Namen `lojban` für das Paket zu reservieren.

Sowohl https://hackage.haskell.org/package/tersmu als auch https://hackage.haskell.org/package/lojbanParser verwenden Pappy, um den Code aus der Grammatik zu generieren. `lojbanParser` hat mehr Downloads und generierte Doku, also würde ich das verwenden.

**Comment by uwap** [comment]
`lojbanParser` sieht auch hinsichtlich der datentypen besser aus.

**Comment by uwap** [comment]
Ich denke wir werden dann `lojbanParser` verwenden. Ich schließe das mal, solange kein weiterer Punkt / keine weiteren Argumente auftauchen.
