### ISSUE TITLE
Bau mit release.nix erzeugt encoding error

### ISSUE THREAD

**Issue by Profpatsch** [lojbanistan/lojbanistan.de#9]
Momentan existiert noch ein Fehler in der `release.nix`:

```
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  [ERROR] jbovlaste.xml: hGetContents: invalid argument (invalid byte sequence)
```

`iconv -f UTF-8 jbovlaste.xml -o /dev/null` gibt Status `0` zurück, also liegt es nicht an der Datei. Vermutlich muss die Locale beim Bau angepasst werden, das hat bei meinen Versuchen bisher aber nicht funktioniert (`  LANG = "en_US.UTF-8";` in die derivation packen).

**Comment by Profpatsch** [comment]
Stack trace (`-prof` und `+RTS -xc -RTS`):

```
*** Exception (reporting due to +RTS -xc): (THUNK), stack trace: 
  Data.Text.Internal.IO.readTextDevice,
  called from Data.Text.Internal.IO.readChunk,
  called from Data.Text.IO.hGetContents,
  called from Data.Text.IO.readFile,
  called from LojbanHighlighting.lojbanCompiler,
  called from LojbanHighlighting.lojbanPandocCompiler,
  called from Main.main
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Hakyll.Main.hakyllWith,
  called from Hakyll.Main.hakyll,
  called from Main.main
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  [ERROR] jbovlaste.xml: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by uwap** [comment]
Nix baut per default ohne LOCALE settings um pure zu bleiben. Unter Arch Linux `env LANG=POSIX cabal run watch` erzeugt den gleichen fehler. Trat der Fehler auch mit `env LANG="de_DE.UTF-8" ${bin} build` auf? Ich verstehe deinen ersten Post so, aber das würde mich echt wundern. Alternativ können wir schauen, ob wir `hGetContents` ein encoding geben können.

**Comment by Profpatsch** [comment]
Ja, komischerweise.

**Comment by uwap** [comment]
Behoben durch 187168e.
